CREATE TABLE metrics.deployments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    build_id VARCHAR(255),
    pass_fail ENUM('pass', 'fail')
);

-- Insert random data
INSERT INTO metrics.deployments (timestamp, build_id, pass_fail)
SELECT
    NOW() - INTERVAL FLOOR(RAND() * 21) DAY - INTERVAL FLOOR(RAND() * 24) HOUR - INTERVAL FLOOR(RAND() * 60) MINUTE,
    CONCAT('build-', FLOOR(RAND() * 10000)),
    IF(RAND() < 0.8, 'pass', 'fail')
FROM
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t1,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t2,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) t3
LIMIT 50;
